# -*- coding: utf-8 -*-
{
    'name': 'KPI Visitas',
    'version':'1.0',
    'category': 'Sales',
    'author': 'CorpoEureka',
    'support': 'proyectos@corpoeureka.com',
    'website' : 'http://www.corpoeureka.com',
    'license' : 'OPL-1',
    'summary': "Administración de visitas en el módulo de ventas",
    'depends': [
    	'base', 
    	'contacts', 
    	'sale_management', 
    	'eu_ve_dates', 
    	'eu_sale_purchase_restante',
    	'eu_partner_approve',
    	'sale_stock',
    	'eu_sales_kpi_kg'
    ],
    'data': [
        'data/data.xml',
        'security/security.xml',
        'security/ir.model.access.csv',
        'wizard/visita_efectiva_views.xml',
        'wizard/visita_no_efectiva_views.xml',
        'views/view_all_traceability.xml',
        'views/action_traceability_view.xml',
        'views/inherited_views.xml',
        'views/res_visit_frequency_views.xml',
        'views/res_partner_views.xml',
        'views/res_visit_views.xml',
        'views/eu_kpi_visit_actions.xml',
        'views/eu_kpi_visit_menus.xml',
        'views/assets.xml',
    ],
    'qweb': [
        "static/src/xml/VisitDashboard.xml",
    ],
}
